language: c

os:
   - linux
   - osx

compiler:
   - gcc
   - clang

before_install:
   - if [[ "x$TRAVIS_OS_NAME" == "xlinux" ]]; then sudo apt-get -qq update; fi
   - if [[ "x$TRAVIS_OS_NAME" == "xosx" ]]; then brew update && brew install homebrew/science/openblas; pushd /usr/include; sudo ln -s $(find . -name cblas.h); popd; fi

matrix:
   allow_failures:
      - os: osx

addons:
   apt:
      packages:
         - gfortran
         - libblas-dev
         - libopenblas-dev
         - libopenblas-base
         - libsuitesparse-dev
         - liblapacke
         - liblapacke-dev

script:
   - ./autogen
   - ./configure
   - make
   - make check
