language: c
sudo: required
dist: trusty

os:
   - linux
   - osx

compiler:
   - gcc
   - clang

before_install:
   - eval "${MATRIX_EVAL}"
   - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
   - if [[ "$CC" == "gcc" && "x$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi
   - echo "" > .env
   - if [[ "x$TRAVIS_OS_NAME" == "xosx" ]]; then printf 'export LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openblas/lib"\nexport CFLAGS="-I/usr/local/include -I/usr/local/opt/openblas/include"\nexport PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"\n' > .env; fi
   - if [[ "x$TRAVIS_OS_NAME" == "xosx" ]]; then brew update; fi

addons:
   apt:
      packages:
         - gfortran
         - libblas-dev
         - libopenblas-dev
         - libopenblas-base
         - libsuitesparse-dev
         - liblapacke
         - liblapacke-dev
         - lcov
   homebrew:
      packages:
         - autoconf
         - automake
         - pkg-config
         - lapack
         - openblas
         - suite-sparse
   coverity_scan:
      project:
         name: "boyle/zedhat"
         description: "Impedance Imaging (EIT and ERT)"
      notification_email: alistair.js.boyle@gmail.com
      build_command_prepend: "./autogen && ./configure"
      build_command: "make"
      branch_pattern: coverity_scan

cache:
   ccache: true
   directories:
      - $HOME/Library/Caches/Homebrew

before_cache:
   - if [[ "x$TRAVIS_OS_NAME" == "xosx" ]]; then brew cleanup; fi

#        - gcc-6
script:
   - ./autogen
   - source .env && ./configure
   - make check
   - if [[ "$CC" == "gcc" && "$TRAVIS_OS_NAME" == "linux" ]]; then make cov; fi

after_failure:
   - awk '/## Summary of the failures. ##/{flag=1;next}/## config.log ##/{flag=0}flag' ${TRAVIS_BUILD_DIR}/*/testsuite.log
#  - cat ${TRAVIS_BUILD_DIR}/*/testsuite.log


after_success:
   - if [[ "$CC" == "gcc" && "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls --exclude tests --gcov-options '\-lp'; fi

env:
   global:
      # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
      #   via the "travis encrypt" command using the project repo's public key
      - secure: "Mm/jdsPpEItqiTbK0KX9KNE1JuL6HJmpbanPV25pYmJNwQVWwCqp1sexk8Fwge2DSpFM9UPSwuqRdrxOfhw7YCFZT+rQ3BaezivSCm4NC3eNswRxWWjCGeYSKqNwIElu7SHZgPXRWmVK9EvmaNmSuJ7HA2xgzmxT46cgT1lwrE7YTFAE1AL/+WKCyh6cCLvUDzm8z6G8ZpRS6X+DEEBfORH4V1zU8wax3G796mvJwYXaPimsNPDm/0tQWG+fduk27ZWkSMoilzyosYEsEBo/lTAqpB1vXK5+KB5y/zZ4STST5EcHBLIgLV/ojXL+rZcNedRrtetFlHq1qxSW1skFrYKBRly3ZuQ7guvznH2fJmucYaM54cJVravpqIfdWwYyLUOe+lWKyPgpyzNSnpAZvoT97bD6kHgT8S54qk8uYTGeGcIL3m38lyy/Xqnt8f+Pr1JHTI7A5tdnNL1GXqP5hzLik/lnoq/SgH2wBF1ljzwB9FxpjhZNzoyrxgIQ54nmo6Mq2WigxzdMaaRJH8GYsUN+B1Xv8ZuHq79kvEQyL/MSbRzLIChsEWQUhNkSmfnzSAElhjaAG3xQqpyv1tHyKuABflBUjuhw46bLnxOEjpxuyrWDXqXBvESu5RZpWV/P11CPhW9eptZ0/7d0eN/1t9dEe7v03GNFTFYcJk5CZxA="
