language: c
sudo: required
dist: trusty

os:
   - linux
#   - osx

compiler:
   - gcc
   - clang

before_install:
   - if [[ "x$TRAVIS_OS_NAME" == "xlinux" ]]; then sudo apt-get -qq update; fi
#   - if [[ "x$TRAVIS_OS_NAME" == "xosx" ]]; then brew update; brew install homebrew/science/openblas; brew install  homebrew/science/suite-sparse; pushd /usr/include; sudo ln -s $(find . -name cblas.h); popd; fi
# missing lapacke... no homebrew to tap

#matrix:
#   allow_failures:
#      - os: osx

addons:
   apt:
      packages:
         - gfortran
         - libblas-dev
         - libopenblas-dev
         - libopenblas-base
         - libsuitesparse-dev
         - liblapacke
         - liblapacke-dev
         - libmatio-dev
         - libmatio2

script:
   - ./autogen
   - ./configure
   - make
   - make check
