#! /bin/bash

# generate ChangeLog from git shortlog
# default directory to put this stuff in is the local one
lcl="."
distdir=${1:-${lcl}}
top_src_dir=${2:-${lcl}}
echo "srcdir=${top_src_dir} distdir=${distdir}"
# eat the two first options
shift
shift
# loop through sequential tags to build ChangeLog
# 0.0.1..0.0.2
# 0.0.2..0.0.3
# etc
#
# rebuild if we can see the git repo and
#  there's no ChangeLog,
#  the ChangeLog is short, or
#  there's newer tags
if ( [[ -d "${top_src_dir}/.git/refs/tags" ]] && \
      ( [[ ! -f "${distdir}/ChangeLog" ]] || \
        [[ $(wc -l "${distdir}/ChangeLog" | cut -f 1 -d ' ' ) -lt 10 ]] || \
        [[ "${top_src_dir}/.git/refs/tags" -nt "${distdir}/ChangeLog" ]] ) ); then
  echo "rebuilding ChangeLog"
  [[ -f "${distdir}/ChangeLog" ]] && rm "${distdir}/ChangeLog"
  touch "${distdir}/ChangeLog"
  [ "$(git rev-list -n 1 master)" != "$(git rev-list -n 1 $(git tag -l | tail -1))" ] && MASTER=master
  T=( $(git tag -l --sort=version:refname "v*") $MASTER )
  for i in $(seq 1 $((${#T[@]}-1)) | tac); do
    {
      printf "%-60s" "Release ${T[$i]}:"
      date --date=- +'%b %d, %Y' --date="$(git show -s --format="%ci" "${T[$i]}" | tail -1)"
      git tag -ln1 ${T[$i]} | sed "s/^${T[$i]} */ -- /"
      git shortlog -w79,3,6 "${T[$i-1]}".."${T[$i]}" | grep -v -e 'minor:' -e '(minor)' -e 'WIP: ' -e '^      '
      echo ""
    } >> "${distdir}/ChangeLog"
  done
else
  echo "opting to NOT rebuild ChangeLog"
fi

echo "get macros"
[ -d m4 ] || mkdir m4
for i in ax_blas ax_check_zlib ax_lapack; do
  [ -f m4/$i.m4 ] || wget "http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/$i.m4" --output-document=m4/$i.m4
done

echo "update configure.ac, etc"
cd "${distdir}" && autoreconf --install --warnings=all --include=m4 "$@"
